# Generated by Django 2.1.2 on 2018-10-05 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, default='', max_length=255, verbose_name='address')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name')),
                ('content_type', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='type')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(db_index=True, default='', max_length=255, verbose_name='content_id')),
                ('content_extension', models.CharField(db_index=True, default='', max_length=255, verbose_name='extension')),
                ('content_name', models.CharField(db_index=True, default='', max_length=255, verbose_name='name')),
                ('content_url', models.CharField(db_index=True, default='', max_length=255, verbose_name='url')),
                ('content_type', models.CharField(db_index=True, default='', max_length=255, verbose_name='type')),
                ('content_filesize', models.IntegerField(verbose_name='filesize')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, default='', max_length=255, verbose_name='message_id')),
                ('subject', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='subject')),
                ('body', models.TextField(blank=True, default='', verbose_name='body')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlook.Email'),
        ),
    ]
