# Generated by Django 2.1.2 on 2018-10-05 14:01

from django.db import migrations, models
import outlook.models.attachments


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_obj',
            field=models.FileField(null=True, upload_to=outlook.models.attachments.attachment_path, verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='olm_filename',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='olm 文件名'),
        ),
        migrations.AddField(
            model_name='email',
            name='olm_filename',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='olm 文件名'),
        ),
        migrations.AddField(
            model_name='email',
            name='olm_url',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='olm 内路径'),
        ),
        migrations.AddField(
            model_name='email',
            name='received_time',
            field=models.DateTimeField(null=True, verbose_name='received_time'),
        ),
        migrations.AddField(
            model_name='email',
            name='topic',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='topic'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_url',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True, verbose_name='url'),
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('olm_filename', 'content_url', 'content_name', 'content_filesize')},
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('olm_filename', 'olm_url', 'message_id')},
        ),
    ]
