# Generated by Django 2.1.2 on 2018-10-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0002_auto_20181005_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='olm_url',
            new_name='olm_item_url',
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('olm_filename', 'olm_item_url', 'message_id')},
        ),
    ]
