# Generated by Django 2.1.2 on 2018-10-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0004_auto_20181006_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True, default='', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='email',
            name='topic',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='topic'),
        ),
    ]
