# Generated by Django 2.1.2 on 2018-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0007_auto_20181006_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='has_html',
            field=models.BooleanField(null=True),
        ),
    ]
