# Generated by Django 2.1.2 on 2018-10-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0008_auto_20181006_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='calendar_accept_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='calendar_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='flag_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='has_richtext',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='inference_classfication',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='is_meeting',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='is_outgoing',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='is_outgoing_meeting_respoonse',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='mentioned_me',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='override_encoding',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='priority',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='receive_representing_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='replyto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='send_read_receipt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='was_sent',
            field=models.BooleanField(null=True),
        ),
    ]
