# Generated by Django 2.1.2 on 2018-10-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0010_auto_20181007_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='bcc_address',
            field=models.ManyToManyField(related_name='bcc_address', to='outlook.Address'),
        ),
        migrations.AddField(
            model_name='email',
            name='cc_addresses',
            field=models.ManyToManyField(related_name='cc_addresses', to='outlook.Address'),
        ),
        migrations.AddField(
            model_name='email',
            name='from_addresses',
            field=models.ManyToManyField(related_name='from_addresses', to='outlook.Address'),
        ),
        migrations.AddField(
            model_name='email',
            name='replyto_addresses',
            field=models.ManyToManyField(related_name='replyto_addresses', to='outlook.Address'),
        ),
        migrations.AddField(
            model_name='email',
            name='to_addresses',
            field=models.ManyToManyField(related_name='to_addresses', to='outlook.Address'),
        ),
    ]
