# Generated by Django 2.1.2 on 2018-10-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0011_auto_20181007_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='bcc_address',
        ),
        migrations.AddField(
            model_name='email',
            name='bcc_addresses',
            field=models.ManyToManyField(related_name='bcc_addresses', to='outlook.Address'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('address', 'name', 'content_type')},
        ),
    ]
