# Generated by Django 2.1.2 on 2018-10-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0012_auto_20181007_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc_addresses',
            field=models.ManyToManyField(related_name='_email_bcc_addresses_+', to='outlook.Address'),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc_addresses',
            field=models.ManyToManyField(related_name='_email_cc_addresses_+', to='outlook.Address'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_addresses',
            field=models.ManyToManyField(related_name='_email_from_addresses_+', to='outlook.Address'),
        ),
        migrations.AlterField(
            model_name='email',
            name='replyto_addresses',
            field=models.ManyToManyField(related_name='_email_replyto_addresses_+', to='outlook.Address'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_addresses',
            field=models.ManyToManyField(related_name='_email_to_addresses_+', to='outlook.Address'),
        ),
    ]
