# Generated by Django 2.1.2 on 2018-10-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0013_auto_20181007_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc_addresses',
            field=models.ManyToManyField(related_name='bcc_address', to='outlook.Address'),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc_addresses',
            field=models.ManyToManyField(related_name='cc_address', to='outlook.Address'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_addresses',
            field=models.ManyToManyField(related_name='from_address', to='outlook.Address'),
        ),
        migrations.AlterField(
            model_name='email',
            name='replyto_addresses',
            field=models.ManyToManyField(related_name='replyto_address', to='outlook.Address'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_addresses',
            field=models.ManyToManyField(related_name='to_address', to='outlook.Address'),
        ),
    ]
