# Generated by Django 2.1.2 on 2018-10-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0014_auto_20181007_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='content_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
    ]
