# Generated by Django 2.1.2 on 2018-10-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0015_auto_20181007_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sender_addresses',
            field=models.ManyToManyField(related_name='sender_address', to='outlook.Address'),
        ),
    ]
