# Generated by Django 2.1.2 on 2018-10-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0016_email_sender_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='references',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
