# Generated by Django 2.1.2 on 2018-10-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0017_auto_20181007_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='references',
            field=models.TextField(blank=True),
        ),
    ]
