# Generated by Django 2.1.2 on 2018-10-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0018_auto_20181007_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='content_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='email',
            name='calendar_accept_status',
            field=models.CharField(blank=True, max_length=263),
        ),
        migrations.AlterField(
            model_name='email',
            name='calendar_message',
            field=models.CharField(blank=True, max_length=269),
        ),
        migrations.AlterField(
            model_name='email',
            name='flag_status',
            field=models.CharField(blank=True, max_length=268),
        ),
        migrations.AlterField(
            model_name='email',
            name='inference_classfication',
            field=models.CharField(blank=True, max_length=265),
        ),
        migrations.AlterField(
            model_name='email',
            name='message_id',
            field=models.CharField(db_index=True, max_length=257, verbose_name='message_id'),
        ),
        migrations.AlterField(
            model_name='email',
            name='olm_item_url',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='olm 内路径'),
        ),
        migrations.AlterField(
            model_name='email',
            name='priority',
            field=models.CharField(blank=True, max_length=266),
        ),
        migrations.AlterField(
            model_name='email',
            name='receive_representing_name',
            field=models.CharField(blank=True, max_length=262),
        ),
        migrations.AlterField(
            model_name='email',
            name='replyto',
            field=models.CharField(blank=True, max_length=261),
        ),
        migrations.AlterField(
            model_name='email',
            name='send_read_receipt',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='email',
            name='source',
            field=models.CharField(blank=True, max_length=267),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, max_length=259),
        ),
        migrations.AlterField(
            model_name='email',
            name='thread_index',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AlterField(
            model_name='email',
            name='thread_topic',
            field=models.CharField(blank=True, db_index=True, max_length=258, verbose_name='thread_topic'),
        ),
    ]
