# Generated by Django 2.1.2 on 2018-10-07 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0020_auto_20181007_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, db_index=True, default='', max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'color')},
        ),
        migrations.AddField(
            model_name='email',
            name='category_list',
            field=models.ManyToManyField(related_name='category_list', to='outlook.Category'),
        ),
        migrations.AddField(
            model_name='email',
            name='primary_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_category', to='outlook.Category'),
        ),
    ]
