# Generated by Django 2.1.2 on 2018-10-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0021_auto_20181007_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='primary_category',
        ),
        migrations.AddField(
            model_name='email',
            name='primary_category',
            field=models.ManyToManyField(related_name='primary_category', to='outlook.Category'),
        ),
    ]
