# Generated by Django 2.1.2 on 2018-10-07 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0022_auto_20181007_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='primary_category',
        ),
        migrations.AddField(
            model_name='email',
            name='primary_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_category', to='outlook.Category'),
        ),
    ]
