# Generated by Django 2.1.2 on 2018-10-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0025_auto_20181007_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='content_url',
            new_name='olm_item_url',
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('olm_filename', 'olm_item_url')},
        ),
    ]
