# Generated by Django 2.1.2 on 2018-10-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0026_auto_20181007_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_extension',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_filesize',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='olm_filename',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='olm_item_url',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
