# Generated by Django 2.1.2 on 2018-10-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0027_auto_20181007_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
