# Generated by Django 2.1.2 on 2018-10-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0029_auto_20181007_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlook.Email'),
        ),
    ]
