# Generated by Django 2.1.2 on 2018-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0031_auto_20181007_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_extension',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
