# Generated by Django 2.1.2 on 2018-10-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0032_auto_20181007_1620'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('olm_filename', 'olm_item_url', 'email')},
        ),
    ]
