# Generated by Django 2.1.2 on 2018-10-07 10:16

from django.db import migrations, models
import outlook.models.attachments


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0033_auto_20181007_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_obj',
            field=models.FileField(max_length=1024, null=True, upload_to=outlook.models.attachments.attachment_path, verbose_name='文件'),
        ),
    ]
