# Generated by Django 2.1.2 on 2018-10-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0034_auto_20181007_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
