# Generated by Django 2.1.2 on 2018-10-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0035_auto_20181007_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=255)),
                ('olm_filename', models.CharField(db_index=True, max_length=255)),
                ('filesize', models.IntegerField()),
                ('hash_value', models.CharField(db_index=True, max_length=255)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='olm',
            unique_together={('filename', 'filesize', 'hash_value')},
        ),
    ]
